name: gitlab
# Increasing this version number *automatically* publishes this package
# when merged into master.
version: 0.5.0
description: A library to communicate with the GitLab API
homepage: https://gitlab.com/exitlive/gitlab-dart
author: Matias Meno <m@tias.me>
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  http: ^0.12.0
  logging: ^0.11.0
  intl: ^0.15.6
  meta: ^1.1.6
dev_dependencies:
  test: ^1.5.0
  path: ^1.6.0
  mockito: ^3.0.0
  grinder: ^0.8.1
  grind_publish: ^0.0.5
